logging:
  path: ./log/

spring:
  redis:
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tiku?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: Ggy101600@
    driver-class-name: com.mysql.cj.jdbc.Driver
